### ISSUE TITLE
Floss not working after running cup all

### ISSUE THREAD

**Issue by pramos** [fireeye/flare-vm#137]
Floss was working in my initial installation of the Flare-VM on Windows 10 VM. 

After running `cup all`

```
C:>floss
Traceback (most recent call last):
  File "C:\Python36\Scripts\floss-script.py", line 11, in <module>
    load_entry_point('floss==1.5.1', 'console_scripts', 'floss')()
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\python36\lib\site-packages\floss\__init__.py", line 3, in <module>
    from utils import ONE_MB
ModuleNotFoundError: No module named 'utils'
```

Please let me know if further information is required or I should move this to the floss project.

**Comment by htnhan** [comment]
Look like the Python interpreter is 3.6. FLOSS does not support Python3. 

I am not sure if cup all on current system automatically update python interpreter as well, which may cause this issue. However, update feature has always been "not fully supported" before version 2.0. If you can, please reinstall FlareVM. We recently pushed a new version that has proper support for update.
