### ISSUE TITLE
Chocolatey error on first installation

### ISSUE THREAD

**Issue by an0th3rhuman** [fireeye/flare-vm#245]
While installing flare VM got this Chocolatey error

```
Boxstarter: Error from Chocolatey:

ErrorRecord                 : Exception calling "Run" with "1" argument(s): "Second path fragment must not be a drive
                              or UNC name.
                              Parameter name: path2"
WasThrownFromThrowStatement : False
Message                     : Exception calling "Run" with "1" argument(s): "Second path fragment must not be a drive
                              or UNC name.
                              Parameter name: path2"
Data                        : {System.Management.Automation.Interpreter.InterpretedFrameInfo}
InnerException              : System.ArgumentException: Second path fragment must not be a drive or UNC name.
                              Parameter name: path2
                                 at System.IO.Path.InternalCombine(String path1, String path2)
                                 at System.IO.FileSystemEnumerableIterator`1.GetFullSearchString(String fullPath,
                              String searchPattern)
                                 at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String
                              originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1
                              resultHandler, Boolean checkHost)
                                 at System.IO.Directory.EnumerateFiles(String path, String searchPattern, SearchOption
                              searchOption)
                                 at NuGet.PhysicalFileSystem.GetFiles(String path, String filter, Boolean recursive)
                                 at NuGet.LocalPackageRepository.<GetPackageFiles>d__31.MoveNext()
                                 at NuGet.LocalPackageRepository.<GetPackages>d__28.MoveNext()
                                 at NuGet.CollectionExtensions.AddRange[T](ICollection`1 collection, IEnumerable`1
                              items)
                                 at NuGet.LocalPackageRepository.FindPackagesById(Func`2 openPackage, String packageId)
                                 at NuGet.PackageRepositoryExtensions.FindPackagesById(IPackageRepository repository,
                              String packageId)
                                 at NuGet.PackageRepositoryExtensions.FindPackage(IPackageRepository repository,
                              String packageId, SemanticVersion version, IPackageConstraintProvider
                              constraintProvider, Boolean allowPrereleaseVersions, Boolean allowUnlisted)
                                 at
                              chocolatey.infrastructure.app.services.NugetService.install_run(ChocolateyConfiguration
                              config, Action`1 continueAction)
                                 at chocolatey.infrastructure.app.services.ChocolateyPackageService.perform_source_runn
                              er_function[T](ChocolateyConfiguration config, Func`2 function)
                                 at chocolatey.infrastructure.app.services.ChocolateyPackageService.install_run(Chocola
                              teyConfiguration config)
                                 at chocolatey.infrastructure.app.runners.GenericRunner.run(ChocolateyConfiguration
                              config, Container container, Boolean isConsole, Action`1 parseArgs)
                                 at chocolatey.infrastructure.app.runners.ConsoleApplication.run(String[] args,
                              ChocolateyConfiguration config, Container container)
                                 at CallSite.Target(Closure , CallSite , Object , Object )
TargetSite                  : Void CheckActionPreference(System.Management.Automation.Language.FunctionContext,
                              System.Exception)
StackTrace                  :    at
                              System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext
                              funcContext, Exception exception)
                                 at
                              System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame
                              frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(Interp
                              retedFrame frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(Interp
                              retedFrame frame)
                                 at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                                 at
                              System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke
                              clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1
                              variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder,
                              Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo,
                              Object[] args)
                                 at
                              System.Management.Automation.ScriptBlock.<>c__DisplayClass57_0.<InvokeWithPipe>b__0()
                                 at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWi
                              thThreadCheck(Action action)
                                 at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope,
                              ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object
                              scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean
                              propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine,
                              Object[] args)
                                 at System.Management.Automation.ScriptBlock.InvokeUsingCmdlet(Cmdlet contextCmdlet,
                              Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder,
                              Object input, Object scriptThis, Object[] args)
                                 at Microsoft.PowerShell.Commands.InvokeCommandCommand.EndProcessing()
                                 at System.Management.Automation.CommandProcessorBase.Complete()
HelpLink                    :
Source                      : System.Management.Automation
HResult                     : -2146233087
```

**Comment by htnhan** [comment]
@an0th3rhuman Can you try the installation again? I have tested the installation in Nov, but did not run into this issue. If you still have issues, can you also upload the following files:
- `%PROGRAMDATA%\chocolatey\logs\chocolatey.log`
- `%PROGRAMDATA%\chocolatey\logs\summary.log`

Thank you,

**Comment by MalwareMechanic** [comment]
@an0th3rhuman We've recently pushed a new update in #280. Please install the new requirements and attempt a FLARE VM installation.

.NET 4.5 https://www.microsoft.com/en-us/download/details.aspx?id=30653
WMF 5.1 https://www.microsoft.com/en-us/download/details.aspx?id=54616
