### ISSUE TITLE
Application Validation did not succeed. Unable to continue.

### ISSUE THREAD

**Issue by tedher** [fireeye/flare-vm#3]
I tried to run the **flarevm_malware.ps1** script directly in Internet Explorer.

Unfortunately in the middle of the process, the application stopped and displayed the following error message "Application Validation did not succeed. Unable to continue".

Below is the detailed error messages:
```
ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of http://boxstarter.org/launch/Boxstarter.WebLaunch.Application?package=https://raw.githubusercontent.com/fireeye/flare-vm/master/flarevm_malware.ps1&https://raw.githubusercontent.com/fireeye/flare-vm/master/flarevm_malware.ps1 resulted in exception. Following failure messages were detected:
		+ File, chocolatey.dll, has a different computed hash than specified in manifest


ERROR DETAILS
	Following errors were detected during this operation.
	* [7/29/2017 10:52:21 PM] System.Deployment.Application.InvalidDeploymentException (HashValidation)
		- File, chocolatey.dll, has a different computed hash than specified in manifest.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, Hash hash)
			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, HashCollection hashCollection)
			at System.Deployment.Application.ComponentVerifier.VerifyComponents()
			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
```
Any advices how to solve this problem?

**Comment by doomedraven** [comment]
execute install.bat

**Comment by tedher** [comment]
I still got the same error messages, even after running the `install.bat`.

**Comment by abhinavbom** [comment]
Facing similar issue. Tried both browser as well as running batch file. Can you please provide a solution.

**Comment by nixawk** [comment]
Modify **C:\ProgramData\chocolatey\config\chocolatey.config**, and disable checksumFiles.

```
<feature name="checksumFiles" enabled="false" setExplicitly="false" description="Checksum files when pulled in from internet (based on package)." />
```

It's not a good idea to disable checksum feature.

**Comment by tedher** [comment]
I fixed this problem by installing [Chocolatey](https://chocolatey.org/) and followed [nixawk](https://github.com/nixawk)'s suggestion to disable the checksumFiles.
