### ISSUE TITLE
Fakenet-NG does not run on windows 10

### ISSUE THREAD

**Issue by htnhan** [fireeye/flare-vm#71]
Traceback: 

Traceback (most recent call last):
 File "C:\Program Files\Python27\Scripts\fakenet-script.py", line 6, in
     from pkg_resources import load_entry_point  
File "c:\program files\python27\lib\site-packages\pkg_resources\__init__.py", line 3017, in @_call_aside  
File "c:\program files\python27\lib\site-packages\pkg_resources\__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)  
File "c:\program files\python27\lib\site-packages\pkg_resources\__init__.py", line 3030, in _initialize_master_working_set
    working_set = WorkingSet._build_master()  
File "c:\program files\python27\lib\site-packages\pkg_resources\__init__.py", line 661, in _build_master
    return cls._build_from_requirements(__requires__)  
File "c:\program files\python27\lib\site-packages\pkg_resources\__init__.py", line 674, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())  
File "c:\program files\python27\lib\site-packages\pkg_resources\__init__.py", line 858, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)pkg_resources.ContextualVersionConflict: (cryptography 2.1.1 (c:\program files\python27\lib\site-packages), Requirement.parse('cryptography>=2.1.4'), set(['pyopenssl']))

**Comment by strictlymike** [comment]
The involvement of `cryptography` and `pyopenssl` makes me wonder if this is related to the FakeNet-NG issue I noted here: [Installation on Windows fails unless cryptography is installed separately](https://github.com/fireeye/flare-fakenet-ng/issues/40).

**Comment by htnhan** [comment]
Confirmed! I recently tested a new installation, and Fakenet works. If reopen, please include the following information:

1. Windows version and build number
2. Python version
3. Installed python libraries.

Thanks,
